name: spacebattle_conflict

on:
  push:
    branches: ["Spaceship_Pool"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore spacebattle

      - name: Test Build
        run: dotnet build Default_game --no-restore /p:ContinuousIntegrationBuild=true

      - name: Run
        run: cd Default_game && dotnet run